name: iOS CI with Carthage

on: workflow_dispatch

jobs:
  iOS:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods Install 
      run: npx pod-install
    - name: Carthage build
      run: carthage build --no-skip-current --use-xcframeworks
    - name: Commit files
      run: |
        git config --local user.email "liamxujia@outlook.com"
        git config --local user.name "nxdm"
        git add .
        git commit -m "`Commit xcframework files '+%Y-%m-%d %H:%M:%S'`"
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: ${{ github.ref }}
